### ISSUE TITLE
switch status not updated

### ISSUE THREAD

**Issue by garagenlager** [Tecotix/livisi-home-assistant#1]
Hi, I´m using the new Livisi integration and found that the switch status is not updated when the status is changed by an automization calling a scene. After reloading the integration, the status is immediately set to the correct value. I´m using the five switches basically as lights and added them to a scene. In an automization, I activated the scene, The light swiches on,  but the status in the dashboard is still like off.

**Comment by Tecotix** [comment]
If it is about the new Livisi integration of Home assistant, you are wrong here. Please post your error directly to Home assistant Livisi integration. 

https://github.com/home-assistant/core/tree/dev/homeassistant/components/livisi

This project was just my own playground and has not been maintained for 2 years.
